In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
x

[8.0, 1, 2.5, 4, 28.0]

In [3]:
x_with_nan

[8.0, 1, 2.5, nan, 4, 28.0]

In [4]:
math.isnan(np.nan), np.isnan(math.nan)

(True, True)

In [6]:
math.isnan(x_with_nan[3]), np.isnan(x_with_nan[3])

(True, True)

In [7]:
y, y_with_nan = np.array(x), np.array(x_with_nan)

In [8]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

In [9]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [10]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [11]:
mean_ = sum(x) / len(x)

In [12]:
mean_

8.7

In [13]:
mean_ = statistics.mean(x)

In [14]:
mean_

8.7

In [15]:
mean_ = statistics.fmean(x)

In [16]:
mean_

8.7

In [17]:
mean_ = statistics.mean(x_with_nan)
mean_

nan

In [18]:
mean_ = y.mean()

In [19]:
mean_

8.7

In [20]:
np.nanmean(y_with_nan)

8.7

In [21]:
z_with_nan.mean()

8.7

In [22]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]
wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
wmean

6.95

In [23]:
y, z, w = np.array(x), pd.Series(x), np.array(w)
wmean = np.average(y, weights=w)

In [24]:
wmean

6.95

In [25]:
hmean = len(x) / sum(1 / item for item in x)

In [26]:
hmean

2.7613412228796843

In [27]:
hmean = statistics.harmonic_mean(x)

In [28]:
hmean

2.7613412228796843

In [29]:
statistics.harmonic_mean([1, 0, 2])

0

In [31]:
statistics.harmonic_mean([1, 2, 2])

1.5

In [32]:
scipy.stats.hmean(y)


2.7613412228796843

In [33]:
median_ = statistics.median(x)

In [35]:
statistics.median_low(x[:-1])

2.5

In [36]:
statistics.median_high(x[:-1])

4

In [37]:
np.nanmedian(y_with_nan)

4.0

In [39]:
u = [2, 3, 2, 8, 12]
mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

In [40]:
mode_ = statistics.mode(u)

In [41]:
mode_

2

In [42]:
mode_ = statistics.multimode(u)

In [43]:
mode_

[2]

In [44]:
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
var_

123.19999999999999

In [45]:
var_ = statistics.variance(x)

In [46]:
var_

123.2

In [47]:
var_ = np.var(y, ddof=1)

In [48]:
var_

123.19999999999999

In [49]:
std_ = var_ ** 0.5

In [50]:
std_

11.099549540409285

In [51]:
std_ = statistics.stdev(x)

In [52]:
std_

11.099549540409287

In [53]:
np.std(y, ddof=1)

11.099549540409285

In [54]:
y.std(ddof=1)

11.099549540409285

In [55]:
np.std(y_with_nan, ddof=1)

nan

In [56]:
y_with_nan.std(ddof=1)

nan

In [57]:
np.nanstd(y_with_nan, ddof=1)

11.099549540409285

In [58]:
z.std(ddof=1)

11.099549540409285

In [59]:
z_with_nan.std(ddof=1)

11.099549540409285

In [60]:
x = [8.0, 1, 2.5, 4, 28.0]
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
std_ = var_ ** 0.5
skew_ = (sum((item - mean_)**3 for item in x) * n / ((n - 1) * (n - 2) * std_**3))
skew_

1.9470432273905929

In [61]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [62]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [63]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

In [64]:
z.skew()

1.9470432273905924

In [65]:
z_with_nan.skew()

1.9470432273905924

In [68]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]
statistics.quantiles(x, n=2)
statistics.quantiles(x, n=4, method='inclusive')

[0.1, 8.0, 21.0]

In [69]:
y = np.array(x)
np.percentile(y, 5)
np.percentile(y, 95)

34.919999999999995

In [71]:
np.percentile(y, [25, 50, 75])
np.median(y)

8.0

In [72]:
y_with_nan = np.insert(y, 2, np.nan)
y_with_nan


array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [73]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])