In [11]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import cross_val_score

In [2]:
X, y = datasets.load_iris(return_X_y=True)

In [3]:
X.shape, y.shape

((150, 4), (150,))

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [5]:
X_train.shape, y_train.shape

((90, 4), (90,))

In [6]:
X_test.shape, y_test.shape

((60, 4), (60,))

In [7]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

In [8]:
clf.score(X_test, y_test)

0.9666666666666667

In [9]:
clf = svm.SVC(kernel='linear', C=1, random_state=42)

In [12]:
scores = cross_val_score(clf, X, y, cv=5)

In [13]:
scores

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [14]:
from sklearn import metrics


In [15]:
scores = cross_val_score(clf, X, y, cv=5, scoring='f1_macro')

In [16]:
scores

array([0.96658312, 1.        , 0.96658312, 0.96658312, 1.        ])

In [17]:
from sklearn.model_selection import ShuffleSplit

In [18]:
n_samples = X.shape[0]

In [19]:
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)

In [20]:
 cross_val_score(clf, X, y, cv=cv)

array([0.97777778, 0.97777778, 1.        , 0.95555556, 1.        ])